apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-matching-server
spec:
  selector:
    matchLabels:
      app: template-matching-server
  template:
    metadata:
      labels:
        app: template-matching-server
    spec:
      containers:
        - name: template-matching-server
          imagePullPolicy: IfNotPresent
          image: latonaio/template-matching-by-opencv-server:latest
          resources: { }
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 50052
          volumeMounts:
            - name: aion-data
              mountPath: /var/lib/aion/Data/
            - name: scripts
              mountPath: /var/lib/aion/Runtime/template-matching-by-opencv-server
      volumes:
        - name: aion-data
          hostPath:
            path: /var/lib/aion/Data/
        - name: scripts
          hostPath:
            path: /home/latona/workspace/template-matching-by-opencv/server
---
apiVersion: v1
kind: Service
metadata:
  name: template-matching-server
spec:
  selector:
    app: template-matching-server
  type: NodePort
  ports:
    - port: 50052
      targetPort: 50052
      nodePort: 30052

