# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/template-matcning.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/template-matcning.proto',
  package='templatematching',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dproto/template-matcning.proto\x12\x10templatematching\x1a\x1cgoogle/protobuf/struct.proto\"%\n\x08Matching\x12\x19\n\x11picture_file_list\x18\x01 \x03(\t\"<\n\x0eMatchingResult\x12*\n\tdata_dict\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"5\n\x03Set\x12.\n\rtemplate_data\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x1b\n\tSetResult\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\xb0\x01\n\x10TemplateMatching\x12\x45\n\rset_templates\x12\x15.templatematching.Set\x1a\x1b.templatematching.SetResult\"\x00\x12U\n\x13get_matching_result\x12\x1a.templatematching.Matching\x1a .templatematching.MatchingResult\"\x00\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_MATCHING = _descriptor.Descriptor(
  name='Matching',
  full_name='templatematching.Matching',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='picture_file_list', full_name='templatematching.Matching.picture_file_list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=118,
)


_MATCHINGRESULT = _descriptor.Descriptor(
  name='MatchingResult',
  full_name='templatematching.MatchingResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_dict', full_name='templatematching.MatchingResult.data_dict', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=180,
)


_SET = _descriptor.Descriptor(
  name='Set',
  full_name='templatematching.Set',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_data', full_name='templatematching.Set.template_data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=235,
)


_SETRESULT = _descriptor.Descriptor(
  name='SetResult',
  full_name='templatematching.SetResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='templatematching.SetResult.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=264,
)

_MATCHINGRESULT.fields_by_name['data_dict'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_SET.fields_by_name['template_data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['Matching'] = _MATCHING
DESCRIPTOR.message_types_by_name['MatchingResult'] = _MATCHINGRESULT
DESCRIPTOR.message_types_by_name['Set'] = _SET
DESCRIPTOR.message_types_by_name['SetResult'] = _SETRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Matching = _reflection.GeneratedProtocolMessageType('Matching', (_message.Message,), {
  'DESCRIPTOR' : _MATCHING,
  '__module__' : 'proto.template_matcning_pb2'
  # @@protoc_insertion_point(class_scope:templatematching.Matching)
  })
_sym_db.RegisterMessage(Matching)

MatchingResult = _reflection.GeneratedProtocolMessageType('MatchingResult', (_message.Message,), {
  'DESCRIPTOR' : _MATCHINGRESULT,
  '__module__' : 'proto.template_matcning_pb2'
  # @@protoc_insertion_point(class_scope:templatematching.MatchingResult)
  })
_sym_db.RegisterMessage(MatchingResult)

Set = _reflection.GeneratedProtocolMessageType('Set', (_message.Message,), {
  'DESCRIPTOR' : _SET,
  '__module__' : 'proto.template_matcning_pb2'
  # @@protoc_insertion_point(class_scope:templatematching.Set)
  })
_sym_db.RegisterMessage(Set)

SetResult = _reflection.GeneratedProtocolMessageType('SetResult', (_message.Message,), {
  'DESCRIPTOR' : _SETRESULT,
  '__module__' : 'proto.template_matcning_pb2'
  # @@protoc_insertion_point(class_scope:templatematching.SetResult)
  })
_sym_db.RegisterMessage(SetResult)


DESCRIPTOR._options = None

_TEMPLATEMATCHING = _descriptor.ServiceDescriptor(
  name='TemplateMatching',
  full_name='templatematching.TemplateMatching',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=267,
  serialized_end=443,
  methods=[
  _descriptor.MethodDescriptor(
    name='set_templates',
    full_name='templatematching.TemplateMatching.set_templates',
    index=0,
    containing_service=None,
    input_type=_SET,
    output_type=_SETRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_matching_result',
    full_name='templatematching.TemplateMatching.get_matching_result',
    index=1,
    containing_service=None,
    input_type=_MATCHING,
    output_type=_MATCHINGRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPLATEMATCHING)

DESCRIPTOR.services_by_name['TemplateMatching'] = _TEMPLATEMATCHING

# @@protoc_insertion_point(module_scope)
